{{ DOCKERFILE_BASE }}

FROM docker4dev_base as docker4kernel

RUN {{ DOCKERFILE_KERNEL_DEP }}

ENV SCRDIR=/opt/scripts
ENV PACDIR=/opt/packages
ENV CODDIR=/opt/codes
ENV SHADIR=/opt/shared

ARG SUBDIR=kerneldev/
ARG FROMDIR=./Local
COPY $FROMDIR/scripts/$SUBDIR  $SCRDIR
COPY $FROMDIR/packages/$SUBDIR $PACDIR
COPY $FROMDIR/codes/$SUBDIR    $CODDIR

RUN mkdir -p $SHADIR
RUN chmod +x $SCRDIR/*
RUN $SCRDIR/deploymentinit.sh

ENTRYPOINT ["bash", "/opt/scripts/start.sh"]
